# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CritEval <- function(X0, q, crit = 0L) {
    .Call(`_UniDOE_CritEval`, X0, q, crit)
}

SATA_UD <- function(n, s, q, init, initX, crit, maxiter, hits_ratio) {
    .Call(`_UniDOE_SATA_UD`, n, s, q, init, initX, crit, maxiter, hits_ratio)
}

SATA_AUD <- function(XP, n, s, q, init, initX, crit, maxiter, hits_ratio) {
    .Call(`_UniDOE_SATA_AUD`, XP, n, s, q, init, initX, crit, maxiter, hits_ratio)
}

SATA_LP <- function(X0, q, crit, maxiter, hits_ratio) {
    .Call(`_UniDOE_SATA_LP`, X0, q, crit, maxiter, hits_ratio)
}

